"""Generates Java from the design sheets: one record/entry/method per row. Run after preflight.

    python -I tools/gen_code.py
Outputs (overwritten every run; never edit by hand):
  fabric/src/main/java/dev/duelcraft/gen/   Settings, MdEncodings, Prompts, Events, Payloads, Decks,
                                            MobDuelists, AiPolicies, ItemSpecs, HookIds, MdAssets
  fabric/src/client/java/dev/duelcraft/client/gen/PromptWidgets.java
"""
import json, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, "design")
MAIN = os.path.join(ROOT, "fabric", "src", "main", "java", "dev", "duelcraft", "gen")
CLIENT = os.path.join(ROOT, "fabric", "src", "client", "java", "dev", "duelcraft", "client", "gen")
S = {f[:-5]: json.load(open(os.path.join(D, f), encoding="utf-8"))["rows"] for f in os.listdir(D) if f.endswith(".json")}
HDR = "// GENERATED by tools/gen_code.py from design/{sheet}.json - do not edit.\n"


def camel(s, upper=False):
    parts = re.split(r"[_\W]+", s)
    out = parts[0].lower() + "".join(p[:1].upper() + p[1:] for p in parts[1:])
    return out[:1].upper() + out[1:] if upper else out


def jstr(s):
    return json.dumps(s, ensure_ascii=False)


def write(dirpath, name, text):
    os.makedirs(dirpath, exist_ok=True)
    with open(os.path.join(dirpath, name), "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


# ---------------------------------------------------------------- layouts -> records + decoders
JT = {"u8": "int", "u16": "int", "u32": "int", "i32": "int", "u64": "long", "loc": "Loc"}
RD = {"u8": "r.u8()", "u16": "r.u16()", "u32": "r.u32()", "i32": "r.i32()", "u64": "r.u64()", "loc": "r.loc()"}


def parse_layout(s):
    """'a:u8, l:list<u32>[x:u32,y:loc]' -> [(name, type, sub)]"""
    fields, i, s = [], 0, s.strip()
    while i < len(s):
        m = re.compile(r"\s*(\w+):(list<(\w+)>\[|(\w+))").match(s, i)
        name = m.group(1)
        if m.group(3):
            depth, j = 1, m.end()
            while depth:
                depth += {"[": 1, "]": -1}.get(s[j], 0)
                j += 1
            fields.append((name, "list", (m.group(3), parse_layout(s[m.end():j - 1]))))
            i = j
        else:
            fields.append((name, m.group(4), None))
            i = m.end()
        m2 = re.compile(r"\s*,?").match(s, i)
        i = m2.end()
    return fields


def gen_record(rec, fields, iface, indent="\t"):
    """returns (java source of record with static read(MsgReader r))"""
    out, comps, reads = [], [], []
    for name, t, sub in fields:
        if t == "list":
            ct, subf = sub
            sub_name = camel(name, True) + "Entry"
            out.append(gen_record(sub_name, subf, None, indent + "\t"))
            comps.append(f"java.util.List<{sub_name}> {name}")
            reads.append(f"r.list(r.{'u8' if ct == 'u8' else 'u32'}(), {sub_name}::read)")
        else:
            comps.append(f"{JT[t]} {name}")
            reads.append(RD[t])
    impl = f" implements {iface}" if iface else ""
    body = f"{indent}public record {rec}({', '.join(comps)}){impl} {{\n"
    body += "".join(out)
    body += f"{indent}\tpublic static {rec} read(MsgReader r) {{\n{indent}\t\treturn new {rec}({', '.join(reads)});\n{indent}\t}}\n"
    body += f"{indent}}}\n"
    return body


def gen_messages(sheet, cls, iface, extra):
    rows = S[sheet]
    src = HDR.format(sheet=sheet) + "package dev.duelcraft.gen;\n\nimport dev.duelcraft.duel.MsgReader;\nimport dev.duelcraft.duel.MsgReader.Loc;\n\n"
    src += f"public final class {cls} {{\n\tprivate {cls}() {{}}\n\n\tpublic sealed interface {iface} permits {', '.join(r['record'] for r in rows)} {{\n\t\tint msgId();\n\t}}\n\n"
    for r in rows:
        rec = gen_record(r["record"], parse_layout(r["layout"]), iface)
        # add msgId() + metadata to the record
        meta = f"\t\t@Override public int msgId() {{ return {r['msgId']}; }}\n"
        for k in extra:
            meta += f"\t\tpublic static final String {k.upper()} = {jstr(str(r[k]))};\n"
        rec = rec.replace(f"implements {iface} {{\n", f"implements {iface} {{\n{meta}", 1)
        src += rec + "\n"
    src += f"\t/** Decodes one message body (after the id byte); null when this sheet has no row for the id. */\n"
    src += f"\tpublic static {iface} decode(int msgId, MsgReader r) {{\n\t\treturn switch (msgId) {{\n"
    for r in rows:
        src += f"\t\t\tcase {r['msgId']} -> {r['record']}.read(r);\n"
    src += "\t\t\tdefault -> null;\n\t\t};\n\t}\n\n"
    for k in extra:
        src += f"\tpublic static String {camel(k)}(int msgId) {{\n\t\treturn switch (msgId) {{\n"
        for r in rows:
            src += f"\t\t\tcase {r['msgId']} -> {jstr(str(r[k]))};\n"
        src += "\t\t\tdefault -> null;\n\t\t};\n\t}\n\n"
    src += "\tpublic static String name(int msgId) {\n\t\treturn switch (msgId) {\n"
    for r in rows:
        src += f"\t\t\tcase {r['msgId']} -> {jstr(r['name'])};\n"
    src += "\t\t\tdefault -> \"MSG_\" + msgId;\n\t\t};\n\t}\n}\n"
    write(MAIN, cls + ".java", src)


gen_messages("duel_prompts", "Prompts", "Prompt", ["uiWidget", "aiPolicy"])
gen_messages("duel_events", "Events", "Event", ["logText", "boardEffect", "sound"])

# AI policies: one abstract method per row; dispatch from prompt -> policy
src = HDR.format(sheet="ai_policies") + "package dev.duelcraft.gen;\n\nimport dev.duelcraft.gen.Prompts.*;\n\n"
src += "/** One method per ai_policies row; DuelAi implements them. Each returns the raw response bytes. */\npublic interface AiPolicies {\n"
by_policy = {}
for p in S["duel_prompts"]:
    by_policy.setdefault(p["aiPolicy"], []).append(p["record"])
for r in S["ai_policies"]:
    for rec in by_policy[r["id"]]:
        src += f"\t/** {r['id']}: {r['rule']} Fallback: {r['fallback']} */\n\tbyte[] {camel(r['id'])}({rec} p, boolean fallback);\n\n"
src += "\tdefault byte[] answer(Prompt p, boolean fallback) {\n\t\treturn switch (p) {\n"
for r in S["duel_prompts"]:
    src += f"\t\t\tcase {r['record']} x -> {camel(r['aiPolicy'])}(x, fallback);\n"
src += "\t\t};\n\t}\n}\n"
write(MAIN, "AiPolicies.java", src)

# UI widgets: one factory method per row; dispatch prompt -> widget
src = HDR.format(sheet="ui_widgets") + "package dev.duelcraft.client.gen;\n\nimport dev.duelcraft.gen.Prompts.*;\n\n"
src += "/** One factory per ui_widgets row; the duel screen implements them. */\npublic interface PromptWidgets<W> {\n"
by_widget = {}
for p in S["duel_prompts"]:
    by_widget.setdefault(p["uiWidget"], []).append(p["record"])
for r in S["ui_widgets"]:
    for rec in by_widget[r["id"]]:
        src += f"\t/** {r['id']} ({r['javaClass']}): {r['shows']} Input: {r['input']} */\n\tW {camel(r['id'])}({rec} p);\n\n"
src += "\tdefault W widgetFor(Prompt p) {\n\t\treturn switch (p) {\n"
for r in S["duel_prompts"]:
    src += f"\t\t\tcase {r['record']} x -> {camel(r['uiWidget'])}(x);\n"
src += "\t\t};\n\t}\n}\n"
write(CLIENT, "PromptWidgets.java", src)

# ---------------------------------------------------------------- settings
src = HDR.format(sheet="settings") + "package dev.duelcraft.gen;\n\npublic final class Settings {\n\tprivate Settings() {}\n\n"
for r in S["settings"]:
    src += f"\t/** {r['doc']} (used by {r['usedBy']}) */\n\tpublic static final {r['type']} {r['key']} = {r['value']};\n\n"
write(MAIN, "Settings.java", src + "}\n")

# ---------------------------------------------------------------- Master Duel encodings
src = HDR.format(sheet="card_kinds, races, attributes, link_markers") + "package dev.duelcraft.gen;\n\nimport java.util.Map;\nimport static java.util.Map.entry;\n\n"
src += "public final class MdEncodings {\n\tprivate MdEncodings() {}\n\n"
src += "\t/** card_kinds: (mdKind << 8 | (mdIcon & 0xFF)) -> {engineType, frameOrdinal}; mdIcon -1 = any (monsters). */\n"
frames = []
for r in S["card_kinds"]:
    if r["frame"] not in frames:
        frames.append(r["frame"])
src += "\tpublic static final String[] FRAMES = {" + ", ".join(jstr(f) for f in frames) + "};\n"
src += "\tpublic static final Map<Integer, int[]> KINDS = Map.ofEntries(\n" + ",\n".join(
    f"\t\tentry({r['mdKind']} << 8 | {r['mdIcon'] & 0xFF}, new int[] {{0x{r['engineType']:x}, {frames.index(r['frame'])}}})" for r in S["card_kinds"]) + ");\n\n"
src += "\tpublic static final Map<Integer, Long> RACES = Map.ofEntries(\n" + ",\n".join(
    f"\t\tentry({r['mdRace']}, {r['engineRace']}L) /* {r['name']} */" for r in S["races"]) + ");\n\n"
src += "\tpublic static final Map<Integer, Integer> ATTRIBUTES = Map.ofEntries(\n" + ",\n".join(
    f"\t\tentry({r['mdAttribute']}, {r['engineAttribute']}) /* {r['name']} */" for r in S["attributes"]) + ");\n\n"
src += "\t/** link_markers: index = Master Duel bit, value = ocgcore bit. */\n\tpublic static final int[] LINK_MARKERS = {" + ", ".join(
    str(r["engineBit"]) for r in sorted(S["link_markers"], key=lambda r: r["mdBit"])) + "};\n"
src += "\tpublic static final Map<Long, String> RACE_NAMES = Map.ofEntries(\n" + ",\n".join(
    f"\t\tentry({r['engineRace']}L, {jstr(r['name'])})" for r in S["races"]) + ");\n"
src += "\tpublic static final Map<Integer, String> ATTRIBUTE_NAMES = Map.ofEntries(\n" + ",\n".join(
    f"\t\tentry({r['engineAttribute']}, {jstr(r['name'])})" for r in S["attributes"]) + ");\n}\n"
write(MAIN, "MdEncodings.java", src)

# ---------------------------------------------------------------- md assets
src = HDR.format(sheet="md_assets") + "package dev.duelcraft.gen;\n\npublic final class MdAssets {\n\tprivate MdAssets() {}\n\n"
for r in S["md_assets"]:
    src += f"\t/** {r['unityType']}: {r['path']} ({r['format']}) */\n\tpublic static final String {r['id'].upper()} = {jstr(r['path'])};\n"
write(MAIN, "MdAssets.java", src + "}\n")

# ---------------------------------------------------------------- payloads
TYPES = {"int": ("int", "buf.writeVarInt({v})", "buf.readVarInt()"), "long": ("long", "buf.writeLong({v})", "buf.readLong()"),
         "bool": ("boolean", "buf.writeBoolean({v})", "buf.readBoolean()"), "string": ("String", "buf.writeUtf({v})", "buf.readUtf()"),
         "bytes": ("byte[]", "buf.writeByteArray({v})", "buf.readByteArray()")}
src = HDR.format(sheet="payloads") + """package dev.duelcraft.gen;

import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.minecraft.resources.Identifier;

public final class Payloads {
\tprivate Payloads() {}

"""
for r in S["payloads"]:
    fs = [f.strip().split(":") for f in r["fields"].split(",")]
    comps = ", ".join(f"{TYPES[t][0]} {n}" for n, t in fs)
    wr = "".join(f"\t\t\t\t{TYPES[t][1].format(v='p.' + n + '()')};\n" for n, t in fs)
    rd = ", ".join(TYPES[t][2] for n, t in fs)
    src += f"""\t/** {r['direction']}, handled by {r['handler']}. */
\tpublic record {r['record']}({comps}) implements CustomPacketPayload {{
\t\tpublic static final Type<{r['record']}> TYPE = new Type<>(Identifier.fromNamespaceAndPath("duelcraft", {jstr(r['id'])}));
\t\tpublic static final boolean TO_CLIENT = {str(r['direction'] == 's2c').lower()};
\t\tpublic static final StreamCodec<RegistryFriendlyByteBuf, {r['record']}> CODEC = StreamCodec.of(
\t\t\t(buf, p) -> {{
{wr}\t\t\t}},
\t\t\tbuf -> new {r['record']}({rd}));

\t\t@Override
\t\tpublic Type<? extends CustomPacketPayload> type() {{
\t\t\treturn TYPE;
\t\t}}
\t}}

"""
write(MAIN, "Payloads.java", src + "}\n")

# ---------------------------------------------------------------- decks (cids resolved by preflight)
resolved = json.load(open(os.path.join(ROOT, "build", "decks_resolved.json")))
src = HDR.format(sheet="decks") + "package dev.duelcraft.gen;\n\npublic final class Decks {\n\tprivate Decks() {}\n\n"
src += "\tpublic record Deck(String id, String displayName, int[] main, int[] extra) {}\n\n"
for r in S["decks"]:
    d = resolved[r["id"]]
    src += f"\t/** {r['displayName']} (used by {r['usedBy']}); Master Duel cids. */\n"
    src += f"\tpublic static final Deck {r['id'].upper()} = new Deck({jstr(r['id'])}, {jstr(r['displayName'])},\n\t\tnew int[] {{{', '.join(map(str, d['main']))}}},\n\t\tnew int[] {{{', '.join(map(str, d['extra']))}}});\n\n"
src += "\tpublic static Deck byId(String id) {\n\t\treturn switch (id) {\n" + "".join(
    f"\t\t\tcase {jstr(r['id'])} -> {r['id'].upper()};\n" for r in S["decks"]) + "\t\t\tdefault -> null;\n\t\t};\n\t}\n}\n"
write(MAIN, "Decks.java", src)

# ---------------------------------------------------------------- mob duelists
src = HDR.format(sheet="mob_duelists") + "package dev.duelcraft.gen;\n\nimport java.util.List;\n\npublic final class MobDuelists {\n\tprivate MobDuelists() {}\n\n"
src += "\tpublic record MobDuelist(String entity, Decks.Deck deck, String title, int rewardCards) {}\n\n\tpublic static final List<MobDuelist> ALL = List.of(\n"
src += ",\n".join(f"\t\tnew MobDuelist({jstr(r['entity'])}, Decks.{r['deck'].upper()}, {jstr(r['title'])}, {r['rewardCards']})" for r in S["mob_duelists"])
src += ");\n\n\t/** The row for an entity type id, falling back to the '*' row. */\n\tpublic static MobDuelist forEntity(String id) {\n"
src += "\t\tMobDuelist any = null;\n\t\tfor (MobDuelist m : ALL) {\n\t\t\tif (m.entity().equals(id)) return m;\n\t\t\tif (m.entity().equals(\"*\")) any = m;\n\t\t}\n\t\treturn any;\n\t}\n}\n"
write(MAIN, "MobDuelists.java", src)

# ---------------------------------------------------------------- items
src = HDR.format(sheet="items") + "package dev.duelcraft.gen;\n\npublic final class ItemSpecs {\n\tprivate ItemSpecs() {}\n\n\tpublic record ItemSpec(String id, int maxStack) {}\n\n"
for r in S["items"]:
    src += f"\t/** {r['javaClass']}: {r['obtain']} */\n\tpublic static final ItemSpec {r['id'].upper()} = new ItemSpec({jstr(r['id'])}, {r['maxStack']});\n"
write(MAIN, "ItemSpecs.java", src + "}\n")

# ---------------------------------------------------------------- hooks
src = HDR.format(sheet="hooks") + "package dev.duelcraft.gen;\n\n/** One constant per hooks row. Code that installs a hook calls installed(); DuelCraft checks all were. */\npublic enum HookIds {\n"
src += ",\n".join(f"\t/** {r['api']} ({r['side']}, {r['system']}): {r['purpose']} */\n\t{r['id'].upper()}({jstr(r['side'])})" for r in S["hooks"])
src += """;

\tpublic final String side;
\tprivate volatile boolean installed;

\tHookIds(String side) {
\t\tthis.side = side;
\t}

\tpublic void installed() {
\t\tinstalled = true;
\t}

\tpublic boolean isInstalled() {
\t\treturn installed;
\t}
}
"""
write(MAIN, "HookIds.java", src)
print("generated", len(os.listdir(MAIN)), "main +", len(os.listdir(CLIENT)), "client files")

# ---------------------------------------------------------------- hint strings
src = HDR.format(sheet="hint_strings") + "package dev.duelcraft.gen;\n\nimport java.util.Map;\nimport static java.util.Map.entry;\n\npublic final class HintStrings {\n\tprivate HintStrings() {}\n\n"
src += "\tpublic static final Map<Integer, String> TEXT = Map.ofEntries(\n" + ",\n".join(
    f"\t\tentry({r['id']}, {jstr(r['text'])}) /* {r['name']} */" for r in S["hint_strings"]) + ");\n}\n"
write(MAIN, "HintStrings.java", src)
print("hint strings:", len(S["hint_strings"]))
